### ISSUE TITLE
Extra Full Stop in Achievements

### ISSUE THREAD

**Issue by Akshit6828** [Amisha328/Amisha328#1]
Hi @Amisha328. I just went through your profile and saw a little correction.

There was an extra full stop in the achievement section as shown below:
![image](https://user-images.githubusercontent.com/57808363/121913483-0f6f6080-cd4f-11eb-861b-573022e221c6.png)

**Comment by Amisha328** [comment]
Thanks a lot @Akshit6828 for making improvements.
